### ISSUE TITLE
Import all issues from zaru/webpush (will be fixed by this fork)

### ISSUE THREAD

**Issue by collimarco** [pushpad/web-push#1]
A list of *all* the issues and pull requests that are currently *open* on `zaru/webpush` and that we are going to fix with this fork:

## Issues
- [x] https://github.com/zaru/webpush/issues/110
- [x] https://github.com/zaru/webpush/issues/109
- [x] https://github.com/zaru/webpush/issues/107
- [x] https://github.com/zaru/webpush/issues/104
- [x] https://github.com/zaru/webpush/issues/102
- [x] https://github.com/zaru/webpush/issues/98
- [x] https://github.com/zaru/webpush/issues/89
- [x] https://github.com/zaru/webpush/issues/52

## Pull requests
- [x] https://github.com/zaru/webpush/pull/106
- [x] https://github.com/zaru/webpush/pull/105
- [x] https://github.com/zaru/webpush/pull/103
- [x] https://github.com/zaru/webpush/pull/101
- [x] https://github.com/zaru/webpush/pull/100
- [x] https://github.com/zaru/webpush/pull/97

**Comment by collimarco** [comment]
Notes:

- Apple Push Service currently has [a bug](https://bugs.webkit.org/show_bug.cgi?id=247128) that cannot be fixed by this gem and you need to set urgency to high as a workaround
- Windows Notification Service has [a bug](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/push-request-response-headers#response-codes) and currently return 406 instead of 429 for rate limiting (it's still in consideration if we should fix this strange behavior inside this gem or not)

**Comment by collimarco** [comment]
All the issues and pull requests that are not listed in the "Notes" are *solved* by this fork.

**Comment by marckohlbrugge** [comment]
> All the issues and pull requests that are not listed in the "Notes" are _solved_ by this fork.

Thanks for your work on this! Could you please clarify what you mean with "Notes" ?

E.g. I noticed the OpenSSL issue isn't resolved yet (`pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError`), but it seems completed in this PR.

**Comment by collimarco** [comment]
@marckohlbrugge The [notes in my comment above](https://github.com/pushpad/web-push/issues/1#issuecomment-1328131590) are issues imported from `zaru/webpush` that aren't solved yet by this fork. In any case we already use this gem in production, so they are not severe issues.

**Comment by marckohlbrugge** [comment]
@collimarco Sorry, I somehow totally missed that second comment with the notes.

I was able to manually pull in some of the changes from https://github.com/zaru/webpush/pull/106 into your branch and it seems to work 👍

**Comment by collimarco** [comment]
@marckohlbrugge The OpenSSL issue is now resolved. You can use this fork with OpenSSL v3.

**Comment by francogp** [comment]
I'm getting  resulted in a `406 Not Acceptable`  since yesterday, from microsoft edge notifications (I sent only 8).

**Comment by collimarco** [comment]
The Apple bug with "urgency" header is resolved now.
