### ISSUE TITLE
Documentation needed for storing subscription

### ISSUE THREAD

**Issue by brian-kephart** [pushpad/web-push#6]
Thanks for your work on this library! I'm having some trouble, though, and wanted to point out what I see as a hole in the documentation.

This line seems to be doing a lot of work.
https://github.com/pushpad/web-push/blob/5326a5f420736cb2aaf3cf8b1fe8eaa1806a1923/README.md?plain=1#L78

I'm not at all sure how to get a representation of the subscription that is suitable for a web request or a database entry. In particular, the `auth` and `p256dh` fields of the subscription are returned as ArrayBuffers, and as a Ruby guy I'm not used to working with those in JS and could use some guidance.

The documentation up to that point worked well for me, and the parts that follow appear to be straightforward. It's only the passing of the subscription object from the frontend to the backend that seems like it could be clearer.

**Comment by brian-kephart** [comment]
It looks like the data is available in a friendlier format after calling `toJSON` on the PushSubscription object.

**Comment by collimarco** [comment]
> It's only the passing of the subscription object from the frontend to the backend that seems like it could be clearer.

You can find an example in this post:

https://blog.pushpad.xyz/2022/04/web-push-notifications-store-the-subscription-in-the-backend-database/
